# Generated by Django 2.2.4 on 2019-09-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbModifierTypeSettingsInfo',
            fields=[
                ('modifier_type_index', models.AutoField(db_column='Index', primary_key=True, serialize=False)),
                ('modifier_type_name', models.CharField(db_column='Type', max_length=30)),
                ('modifier_type_name_ko', models.CharField(db_column='TypeKo', max_length=50)),
                ('increase_coefficient', models.IntegerField(db_column='Coefficient')),
            ],
            options={
                'db_table': 'tbModifierTypeSettingsInfo',
            },
        ),
        migrations.CreateModel(
            name='TbModifierSettingsInfo',
            fields=[
                ('modifier_index', models.IntegerField(db_column='Index', primary_key=True, serialize=False)),
                ('modifier_name', models.CharField(db_column='Name', max_length=100, unique=True)),
                ('default_value', models.FloatField(db_column='DefaultValue')),
                ('description', models.CharField(db_column='Description', max_length=255)),
                ('description_ko', models.CharField(db_column='DescriptionKo', max_length=255)),
                ('effect_type', models.CharField(db_column='EffectType', max_length=30)),
                ('invested_point', models.IntegerField(db_column='CurrentValue')),
                ('modifier_type', models.ForeignKey(db_column='ModifierType', on_delete=django.db.models.deletion.CASCADE, related_name='modifier_type', to='backend.TbModifierTypeSettingsInfo')),
            ],
            options={
                'db_table': 'tbModifierSettingsInfo',
            },
        ),
    ]
